services:
  account-service:
    build:
      context: ./account-service   # Go into the subfolder[cite: 1, 2]
      dockerfile: Dockerfile        # Look for the file inside that folder[cite: 1, 2]
    container_name: account-service
    ports:
      - "8080:8080"
      - "5005:5005"  # The debug port
    environment:
      #- SPRING_JPA_DATABASE=POSTGRESQL
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/accounts_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      db:
        condition: service_healthy
    networks:
      - banking-network

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service

    ports:
      - "8082:8080"
    environment:
      #- SPRING_JPA_DATABASE=POSTGRESQL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transactions_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      # This is the "Magic" line: use the container name, not localhost
      - ACCOUNT_SERVICE_URL=http://account-service:8080
    networks:
      - banking-network
    depends_on:
      - account-service

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      #- POSTGRES_DB=accounts_db
      - POSTGRES_PASSWORD=password
      # Notice we removed POSTGRES_DB here so it falls back to your custom script
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Maps your script into Postgres
    networks:
      - banking-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  banking-network:
    driver: bridge