spring:
  application:
    name: transaction-service

    # Point to your local port that is mapped to Docker

  datasource:

    # Syntax: ${VARIABLE_NAME:DEFAULT_VALUE}
     url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1}
     username: ${SPRING_DATASOURCE_USERNAME:sa}
     password: ${SPRING_DATASOURCE_PASSWORD:password}
     driverClassName: org.h2.Driver

    # PostgreSQL Connection
    # url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/accounts_db}
    # username: ${SPRING_DATASOURCE_USERNAME:postgres}
    # password: ${SPRING_DATASOURCE_PASSWORD:password}
    # driver-class: name=org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true # Crucial: See the SQL generated for your transfers

    #properties:hibernate:dialect:  org.hibernate.dialect.PostgreSQLDialect

  # This allows you to see the DB in your browser at http://localhost:8080/h2-console
  # JPA / Hibernate
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED:true} #for docker
      path: /h2-console
      # Allow the console to be accessed via the web
      settings:
        web-allow-others: ${SPRING_H2_CONSOLE_SETTINGS_WEB-ALLOW-OTHERS:true}

  # 1. Stop ignoring "nama" and start complaining about it
  jackson:
    deserialization:
      fail-on-unknown-properties: true

      # 2. Make sure Enums are handled strictly
      read-unknown-enum-values-as-null: false
account:
  service:
    url: http://localhost:8080
server:
  port: 8082