server:
  port: 8082

spring:
  application:
    name: transaction-service

  datasource:
    # Syntax: ${VARIABLE_NAME:DEFAULT_VALUE}
    # Defaults to H2 for quick local 'mvn clean compile'
    # Docker will override this with: jdbc:postgresql://db:5432/accounts_db

     url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:transaction_db;DB_CLOSE_DELAY=-1}
     username: ${SPRING_DATASOURCE_USERNAME:sa}
     password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    # Auto-detects the database type (H2 or POSTGRESQL)
    #database: ${SPRING_JPA_DATABASE:H2} #as we have dialect defined explicitly.
    hibernate:
      ddl-auto: update
    show-sql: true # Crucial: See the SQL generated for your transfers

  properties:
    hibernate:
      #This makes the console output much more readable, telling you exactly which Repository method triggered which SQL query.
      format_sql: true

      #use_sql_comments: true
      dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
      # Dialect is usually auto-detected, but we can nudge it

    # H2 Console - Only active when using H2
  h2:
    console:
      enabled: true
      path: /h2-console
      # Allow the console to be accessed via the web
      settings:
        web-allow-others: true

  # Strict Data Handling
  jackson:
    deserialization:
      # If Transaction Service sends a field we don't recognize, CRASH (don't ignore)
      fail-on-unknown-properties: true

      # Enums must match exactly
      read-unknown-enum-values-as-null: false

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8080} # Default for local dev

