spring:
  application:
    name: account-service

  datasource:
    #url: jdbc:h2:mem:bankdb
    # Defaults to H2 for quick local 'mvn clean compile'
    # Docker will override this with: jdbc:postgresql://db:5432/accounts_db
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:accounts_db;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    #driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

  jpa:
    # Auto-detects the database type (H2 or POSTGRESQL)
    database: ${SPRING_JPA_DATABASE:H2}
    hibernate:
      ddl-auto: update

    # Crucial for debugging the "Missing ID" issue
    # Crucial: See the SQL generated for your transfers
    show-sql: true

    properties:
      hibernate:
        #This makes the console output much more readable, telling you exactly which Repository method triggered which SQL query.
        format_sql: true
        use_sql_comments: true
        # Dialect is usually auto-detected, but we can nudge it
        #dialect: ${ç:org.hibernate.dialect.H2Dialect}

  # H2 Console - Only active when using H2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # Strict Data Handling
  jackson:
    deserialization:
      # 1. Stop ignoring "nama" and start complaining about it
      # If Transaction Service sends a field we don't recognize, CRASH (don't ignore)
      fail-on-unknown-properties: true
      # 2. Make sure Enums are handled strictly
      # Enums must match exactly
      read-unknown-enum-values-as-null: false

# Logging configuration to track the Feign client handoff
logging:
  level:
    root: INFO
    com.yourpackage.accountservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # See the actual values being saved